# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c7c4ee1495cf9e400a43b6d53387fa49b7bb54c4bbc7c41da8230479c99e7a1b418f8073980a93cd8eee82f4c0e3c473507b15e293b187b0a5f849971b44cab4

test:
  secret_key_base: 446770a989e2b7350a30da5a6f8c07ce53634636ad124e0efe385dcee98dc11a99689cfe27f4033d3e5a0d08c56f1e41841b0bcf411e4c66e4e8d62853054239

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
